name: component_temple
version: 0.0.1
description: >
  A library for creating architecturally beautiful
  GUI interfaces. The central of it is the idea of an
  hierarchy of components reacting to events and behaving
  themselves in various differen ways visible to users.
  on the project homepage.

  It can be used a stand alone library, on one-page webapps or
  on ones with multiple pages (content oriented websites that care
  about SEO).

  Read a very thorough (but simple to follow!) explanation
  on the project homepage.

homepage:      http://temple.snitko.ru/component-temple
documentation: http://temple.snitko.ru/component-temple/doc

dependencies:

dev_dependencies:
  unittest: any
